# ansible/playbook.yml
---
- hosts: webservers
  become: true # Потрібні права sudo для встановлення пакетів

  tasks:
    - name: Update apt cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
      become: true

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
      become: true

    - name: Install Flask dependency
      pip:
        name: Flask
        state: present

    - name: Create application directory
      file:
        path: /home/ubuntu/flask_app
        state: directory
        mode: '0755'

    - name: Copy Flask application files
      copy:
        src: ../app.py
        dest: /home/ubuntu/flask_app/app.py

    - name: Run Flask application (using nohup to run in background)
      command: nohup python3 /home/ubuntu/flask_app/app.py &
      args:
        chdir: /home/ubuntu/flask_app
      become: false # Запуск від користувача ubuntu, sudo не потрібен
